### ISSUE TITLE
Sharing buttons not working when using dynamicEl

### ISSUE THREAD

**Issue by arl1nd** [sachinchoolur/lg-share#2]
Hi there,

I am initializing lightgallery box with `dynamicEl` property. There is an error when trying to access jQuery function:

http://drops.laborator.co/1kwYB

I have logged the output of `_this.core.$items` outputs an array (not a jQuery object):

http://drops.laborator.co/ETRk

Can you please take care of this and provide a fix?

EDIT:
I've submitted a patch for this, [check it here](https://github.com/sachinchoolur/lg-share/pull/3)

**Comment by sachinchoolur** [comment]
https://github.com/sachinchoolur/lg-share/pull/3
